---
# Run the project code formatters.
#
# Follow the instructions for "Building from Source" in INSTALL.md to install
# the required dependencies.
#
# Usage
# -----
#
# Run the pre-commit hooks on all files using:
#
#     $ pre-commit run --all-files
#
# The pre-commit git hook is installed using:
#
#     $ make init
#
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.9  # or whatever Python version you're using
  
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.9
  
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        language_version: python3.9